version: '3'

services:
  db:
    build:
      context: ./data/mysql/
      dockerfile: Dockerfile
    volumes:
      - "./data/mysql:/docker-entrypoint-initdb.d"
    ports: 
      - "3306:3006"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techtest
      MYSQL_USER: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: root:root@(db:3306)/techtest
      DB_TYPE: "mysql"
      PORT: ":5000"
    ports: 
      - "5000:5000"
    links:
        - db