version: '3'

services:
  db:
    build:
      context: ./data/mysql/
      dockerfile: Dockerfile
    volumes:
      - "./data/mysql:/var/lib/mysql/techtest"
    ports: 
      - "3306:3006"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: root:root@(db:3306)/techtest
      DB_TYPE: "mysql"
      PORT: ":5000"
    ports: 
      - "5000:5000"
    links:
        - db